//////////////////////////////////////////////////////
/*
createAsyncThunk solves the problem where we might need to represent different states
like loading and potentially error when doing asynchronous operations like fetchin data

Since a request is not instantaneous but like Component
   ↓
GET /api/tasks
   ↓
      Server
   ↓
Response
   ↓
Component

without createAsyncThunk we could manually create actions such as
FETCH_TASKS_REQUEST
FETCH_TASKS_SUCCESS
FETCH_TASKS_FAILURE
and manually dispatch them

createAsyncThunk automates this pattern
export const fetchTasks = createAsyncThunk(
  "tasks/fetchTasks",
  async () => {
    const response = await fetch("/api/tasks");

    return response.json();
  }
);
when we create thunks like this,

RTK automatically creates three action types for us
tasks/fetchTasks/pending
tasks/fetchTasks/fulfilled
tasks/fetchTasks/rejected
             fetchTasks()
                  │
                  ↓
             ┌─────────┐
             │ pending │
             └─────────┘
                  │
              API request
             ↙           ↘
        successful       failed
           ↓                ↓
      fulfilled          rejected

Then we can use extraReducers to tell the slice what to do when those actions occur

Suppose our tasks look like
type Task = {
  id: string;
  title: string;
  completed: boolean;
};

Our redux state might be
type TaskState = {
  items: Task[];
  loading: boolean;
  error: string | null;
};

const initialState: TaskState = {
  items: [],
  loading: false,
  error: null,
};

Now when this async thunk below is created
import { createAsyncThunk } from "@reduxjs/toolkit";

export const fetchTasks = createAsyncThunk(
  "tasks/fetchTasks",
  async () => {
    const response = await fetch(
      "https://example.com/api/tasks"
    );

    return response.json();
  }
);
There are two important arguments here
1. tasks/fetchTasks - this is the action type prefix that identifies the thunk
2. async () => ... is the actual asynchronous function

We can think of it as "When somebody dispatches fetchTasks, execute this function"

What happens when we dispatch it?
const dispatch = useAppDispatch()
dispatch(fetchTasks())

The above is different from 
dispatch(setFilterStatus("completed"))

setFilterStatus() represents a normal synchronous action.
fetchTasks() represents an asynchronous workflow.

Now the sequence becomes
dispatch(fetchTasks())
          │
          ↓
    pending action
          │
          ↓
    execute async function
          │
          ↓
    fetch("/api/tasks")
          │
       ┌──┴──┐
       ↓     ↓
    success failure
       ↓     ↓
  fulfilled rejected


Now extraReducers enters the picture, where the slice can listen for those automatically generated actions
import { createSlice } from "@reduxjs/toolkit";

const taskSlice = createSlice({
  name: "tasks",

  initialState,

  reducers: {
    addTask: (state, action) => {
      state.items.push(action.payload);
    },
  },

  extraReducers: (builder) => {
    builder
      .addCase(fetchTasks.pending, (state) => {
        state.loading = true;
        state.error = null;
      })

      .addCase(fetchTasks.fulfilled, (state, action) => {
        state.loading = false;
        state.items = action.payload;
      })

      .addCase(fetchTasks.rejected, (state) => {
        state.loading = false;
        state.error = "Failed to fetch tasks";
      });
  },
});

The actions 
fetchTasks.pending
fetchTasks.fulfilled
fetchTasks.rejected

are not defined inside
reducers: {}, but are generated by createAsyncThunk, therefore the slice responds to them using extraReducers
*/